<?php


class cenikClass extends zakladniKamenClass
{

    protected $db_zona_id;
    protected $cena_tam;
    protected $cena_zpet;
    protected $max_osob;
    protected $min_osob;
    protected $vozidlo_id;


    protected function zakladniVypis()
    {
        // TODO: Implement zakladniVypis() method.
    }

    protected function zakladniHtmlVypis()
    {
        // TODO: Implement zakladniHtmlVypis() method.
    }

    public function getTableName()
    {
        return "s7_cenik";
    }

    public function getInterfaceTypes()
    {
        return parent::getInterfaceTypes(); // TODO: Change the autogenerated stub
    }
}